### ISSUE TITLE
WSL ubuntu can not install Rust

### ISSUE THREAD

**Issue by bonfy** [bonfy/problems#19]
```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

info: Defaulting to 500.0 MiB unpack ram
info: installing component 'clippy' 
info: installing component 'rust-docs' 
 12.2 MiB /  12.2 MiB (100 %) 622.4 KiB/s in  1m 20s ETA:  0s 
info: retrying renaming '/root/.rustup/tmp/3_abwlq15zuecmmg_dir/rust-docs/share/doc/rust/html' to '/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html'
thread 'main' panicked at 'assertion failed: `(left == right)` 
  left: `22`, 
 right: `4`', src/libstd/sys/unix/thread.rs:179:21 
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'No process instance', src/currentprocess.rs:126:17 
stack backtrace:
   0:     0x7f3c898daffd - backtrace::backtrace::libunwind::trace::h812748238d609e46 
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x7f3c898daffd - backtrace::backtrace::trace_unsynchronized::h7c97e818aebf09c8
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x7f3c898daffd - std::sys_common::backtrace::_print_fmt::h60d914263b0ccd71 
                               at src/libstd/sys_common/backtrace.rs:78 
   3:     0x7f3c898daffd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf78227137afc7565
                               at src/libstd/sys_common/backtrace.rs:59 
   4:     0x7f3c8956524c - core::fmt::write::h543cdf60775f89bf 
                               at src/libcore/fmt/mod.rs:1069
   5:     0x7f3c898da904 - std::io::Write::write_fmt::h0c7f3ce24c679426 
                               at src/libstd/io/mod.rs:1504 
   6:     0x7f3c898da105 - std::sys_common::backtrace::_print::h80e55e24be231368 
                               at src/libstd/sys_common/backtrace.rs:62 
   7:     0x7f3c898da105 - std::sys_common::backtrace::print::h3b197b9c1261c865 
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7f3c898da105 - std::panicking::default_hook::{{closure}}::ha6c807149ce20f8f                               at src/libstd/panicking.rs:198 
   9:     0x7f3c898d98f4 - std::panicking::default_hook::he49a9c12e358cc45 
                               at src/libstd/panicking.rs:218
  10:     0x7f3c898d93b6 - std::panicking::rust_panic_with_hook::h93f74f5ef2f71f31 
                               at src/libstd/panicking.rs:515 
  11:     0x7f3c89778064 - std::panicking::begin_panic::h8cc8dbc25d6e865f 
  12:     0x7f3c89776bf8 - rustup::currentprocess::home_process::h3bd9211416f58185 
  13:     0x7f3c89775431 - rustup::cli::term2::stderr::ha11a038386f65e41 
  14:     0x7f3c897791d6 - rustup::cli::log::info_fmt::h01c1460dfbd2eda9 
  15:     0x7f3c897adc72 - rustup::cli::common::set_globals::{{closure}}::ha7a3fb8d7580c5c4
  16:     0x7f3c897c529b - rustup::toolchain::Toolchain::from::{{closure}}::h8ea5d633728aafac
  17:     0x7f3c89836ecd - core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call::hf1992cf24723239a 
  18:     0x7f3c897fd30c - core::ptr::drop_in_place::hf7f8918e368d4625 
  19:     0x7f3c897fd06b - <rustup::dist::component::package::DirectoryPackage as rustup::dist::component::package::Package>::install::h89e535f8cf85d1f2 
  20:     0x7f3c8982a11b - <rustup::dist::component::package::TarGzPackage as rustup::dist::component::package::Package>::install::h6c71d2cc58a3e50f 
  21:     0x7f3c897e5af2 - rustup::dist::manifestation::Manifestation::update::hacf67fad3b44f03a
  22:     0x7f3c897d563c - rustup::dist::dist::update_from_dist_::h1462627f9c58c494 
  23:     0x7f3c897d227a - rustup::install::InstallMethod::install::hbb6430b2dfaf5792 
  24:     0x7f3c897d0d21 - rustup::toolchain::DistributableToolchain::install_from_dist::h7b9bf9317c9aa2c5
  25:     0x7f3c898c5aa2 - rustup::cli::self_update::install::h8ca0f61a773526a9 
  26:     0x7f3c898cbd3d - rustup::cli::setup_mode::main::h4d335e1871435d70 
  27:     0x7f3c894df42a - rustup_init::main::h22da971c634937a2 
  28:     0x7f3c898f3e83 - std::rt::lang_start_internal::{{closure}}::{{closure}}::h4ed4ab1fb893cc93
                               at src/libstd/rt.rs:52 
  29:     0x7f3c898f3e83 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1f01c818c00c4f70
                               at src/libstd/sys_common/backtrace.rs:130 
  30:     0x7f3c894e053f - main 
  31:     0x7f3c890170b3 - __libc_start_main 
  32:     0x7f3c894db029 - <unknown> 
thread panicked while panicking. aborting.
Illegal instruction (core dumped) 
```

**Comment by bonfy** [comment]
缺内存

可以  dd 物理内存 挂载  swapon
